# Generated by Django 6.0 on 2025-12-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='authon',
            new_name='author',
        ),
    ]
