# Generated by Django 6.0.1 on 2026-01-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_followmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='following', to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followers', to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.usermodel'),
        ),
    ]
