MESSAGES = {
    "000": "SUCCESS",

    "ERROR_100": "INVALID_CREDENTIALS",
    "ERROR_101": "USER_NOT_FOUND",

    "ERROR_200": "EMAIL_EXISTS",
    "ERROR_201": "WEAK_PASSWORD",

    "ERROR_000": "VALIDATION_FAILED",
    "ERROR_999": "GENERIC_ERROR",
}
